[package]
name = "integration_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
game_core = {path = "../game_core"}
logging = {path = "../logging"}
rules = {path = "../rules"}
rand = "0.8.5"